### ISSUE TITLE
Images alignment is bad / resolution is poor

### ISSUE THREAD

**Issue by AlexVCaron** [nf-neuro/website#28]
In `create you pipeline / setup your computer`, there are quite a few images. However, right now they are rendered at most at their resolution, making so they don't fit the screen nicely. We can add a few pieces of code in **css** to manage with it :

- Centering (looks okay, but still hurts) :
  ```css
  img {
      display: block;
      margin-left: auto;
      margin-right: auto;
  }
  ```
- Resize to fit screen (images are pixelated) :

  ```css
  img {
      width: 100%
  }
  ```

We need a little investiguation to determine what would do the trick. Nevertheless, we'll have to redo some screenshotting, maybe on a better screen or with a tool that can upsample the screen resolution.
